// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SundayAppProducer;
using System;

namespace SundayAppProducer.Migrations
{
    [DbContext(typeof(MunicipalityContext))]
    [Migration("20181127170850_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("SundayAppProducer.Municipality", b =>
                {
                    b.Property<int>("MunicipalityId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("MunicipalityId");

                    b.ToTable("Municipality");
                });

            modelBuilder.Entity("SundayAppProducer.Range", b =>
                {
                    b.Property<int>("RangeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MunicipalityId");

                    b.Property<DateTime>("RangeEnd");

                    b.Property<string>("RangeName");

                    b.Property<DateTime>("RangeStart");

                    b.Property<double>("RangeTax");

                    b.HasKey("RangeId");

                    b.HasIndex("MunicipalityId");

                    b.ToTable("Ranges");
                });

            modelBuilder.Entity("SundayAppProducer.Range", b =>
                {
                    b.HasOne("SundayAppProducer.Municipality")
                        .WithMany("Ranges")
                        .HasForeignKey("MunicipalityId");
                });
#pragma warning restore 612, 618
        }
    }
}
